config/routes.rb
Rails.application.routes.draw do

  root :to => 'dashboards#index'

  resources :dashboards
  resources :customers do 
    resources :measurements

    member do 
      get 'get_customer_measurements'
    end
  end
  resources :orders
  resources :staffs
  resources :salaries  

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/staff.rb
class Staff < ApplicationRecord
  has_many :orders
  has_many :salaries
  belongs_to :user
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController

  before_action :authenticate_user!
  
  def index
    @staffs = Staff.where(:staff_delete=>'0')
  end

  def show
    @staff = Staff.find(params[:id])
    @staff_salary = Salary.where(:staff_id=>params[:id])
  end

  def new
    @staff = Staff.new
  end

  def create    
    @staff = current_user.staffs.create(staff_params)

    if @staff.present?
      redirect_to staffs_path, :notice=> 'Staff was successfully created.'
    else
      redirect_to new_staffs_path, :alert=> 'Staff was not created.'
    end
  end

  def edit
    @staff = Staff.find(params[:id])
  end

  def update
    @staff = Staff.find(params[:id])

    if @staff.update(staff_params)
      redirect_to staffs_path, :notice=> 'Staff was successfully updated.'
    else
      redirect_to edit_staffs_path, :alert=> 'Staff was not updated.'
    end
  end

  def destroy
    if @order = Staff.where(:id=>params[:id]).update_all(:staff_delete=>'1')
      redirect_to staffs_path
    end
  end
private
  def staff_params
    params.require(:staff).permit(:staff_name, :staff_phone, :staff_email, :staff_sex, :staff_address, :staff_salary, :staff_delete)
  end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/edit.html.erb
                <% content_for :title, "Edit Staff" %>


				<!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Edit Staff <small>Edit Existing Staff Data.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Dashbord</li>
                                <li><a class="link-effect" href="">Edit Staff</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="block">
                                <div class="block-header">
                                    <ul class="block-options">
                                        <li>
                                            <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                                        </li>
                                        <li>
                                            <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                                        </li>
                                    </ul>
                                    <h3 class="block-title">Staff Form <small>Requierd</small></h3>
                                </div>
                                <div class="block-content block-content-narrow">
                                    <div class="row">
                                        <div class="col-md-6 col-md-offset-3">
                                            <%= form_for @staff, :html=>{:class=>'form-horizontal push-10-t'} do|f| %>
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Name</label>
                                                    <div class="col-sm-12">
                                                        <%= f.text_field :staff_name, :class=>'form-control', :placeholder=>"Enter Staff Name", :required=>''  %>
                                                    </div>                                              
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Phone Number</label>
                                                    <div class="col-sm-12">                                          
                                                        <%= f.text_field :staff_phone, :class=>'form-control', :placeholder=>"Enter Staff Phone", :required=>''  %>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Email</label>
                                                    <div class="col-sm-12">                                          
                                                        <%= f.text_field :staff_email, :class=>'form-control', :placeholder=>"Enter Staff Email", :type=>'email', :required=>''  %>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label class="col-xs-12" for="example-password-input">Sex</label>
                                                            <div class="col-sm-12"> 
                                                                <%= f.select :staff_sex, options_for_select([ 'Male', 'Female'], :selected => 'f.staff_sex'), {:include_blank => false}, {:class=>'form-control'} %>
                                                            </div>
                                                        </div>
                                                    </div> 
                                                    <div class="col-md-6"> 
                                                        <div class="form-group">
                                                            <label class="col-xs-12" for="example-password-input">Salary</label>
                                                            <div class="col-sm-12">                                            
                                                                <%= f.text_field :staff_salary, :class=>'form-control', :placeholder=>"Enter Total Salary", :type=>'number', :required=>''  %>
                                                             
                                                            </div>
                                                        </div>  
                                                    </div>                                              
                                                </div>                                      
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Address</label>
                                                    <div class="col-sm-12">                                           
                                                        <%= f.text_area :staff_address, :class=>'form-control', :placeholder=>"Enter Staff Address", :rows=>'2', :required=>''  %>
                                                    </div>
                                                </div>                                               
                                      
                                                <div class="form-group">
                                                    <div class="col-sm-12">
                                                        <%= f.submit :class=>'btn btn-sm btn-primary', :value=>'submit' %>
                                                    </div>
                                                </div>

                                            <% end %>
                                        </div>    
                                    </div>    
                                </div>                                   
                            </div>
                        </div>
                    </div>        
                </div>

app/views/staffs/index.html.erb
                <% content_for :title, "Staffs" %>


  				<!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Staff <small>All Staffs Data.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Dashbord</li>
                                <li><a class="link-effect" href="">Staff</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                    <!-- Dynamic Table Simple -->
                    <div class="block">
                        <div class="block-header">
                            <ul class="block-options">
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                                </li>
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                                </li>
                            </ul>
                            <h3 class="block-title">Staff <small>Records</small></h3>
                        </div>
                        <div class="block-content table-responsive">
                            <!-- DataTables init on table by adding .js-dataTable-simple class, functionality initialized in js/pages/base_tables_datatables.js -->
                            <table class="table table-striped js-dataTable-full-pagination">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
									    <th>Phone</th>
									    <th>Email</th>
									    <th>sex</th>
									    <th>Address</th>
									    <th>Salary</th>
									    <th class="text-center">Actions</th>
                                    </tr>
                                </thead> 
                                <tbody>
                                  <% @staffs.each do |staff|  %>
                                    <tr>
                                        <td>S-<%= staff.id %></td>
                                        <td><%= staff.staff_name %></td>
								        <td><%= staff.staff_phone %></td>
								        <td><%= staff.staff_email %></td>
								        <td><%= staff.staff_sex %></td>
								        <td><%= staff.staff_address %></td>
								        <td><%= staff.staff_salary %></td>
                                        <td class="text-center">
                                            <div class="btn-group">
                                                <%= link_to staff_path(staff.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-eye"></i>
                                                <% end %>
                                                <%= link_to edit_staff_path(staff.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-pencil"></i>
                                                <% end %>
                                                <%= link_to staff_path(staff.id), :class=>'btn btn-xs btn-default', method: :delete, data: {confirm: 'Are you sure?'} do %>
                                                    <i class="fa fa-trash-o"></i>
                                                <% end %>  
                                            </div>      
                                        </td>    
                                    </tr>
                                  <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div>   
                </div>
                <!-- END Page Content -->

app/views/staffs/new.html.erb
                <% content_for :title, "Add Staff" %>


				<!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Add Staff <small>Add New Staff Data.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Dashbord</li>
                                <li><a class="link-effect" href="">Add Staff</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="block">
                                <div class="block-header">
                                    <ul class="block-options">
                                        <li>
                                            <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                                        </li>
                                        <li>
                                            <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                                        </li>
                                    </ul>
                                    <h3 class="block-title">Staff Form <small>Requierd</small></h3>
                                </div>
                                <div class="block-content block-content-narrow">                                    
                                    <div class="row">
                                        <div class="col-md-6 col-md-offset-3">
                                            <%= form_for @staff, :html=>{:class=>'form-horizontal push-10-t'} do|f| %>
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Name</label>
                                                    <div class="col-sm-12">
				                                        <%= f.text_field :staff_name, :class=>'form-control', :placeholder=>"Enter Staff Name", :required=>''  %>
				                                    </div>				                                
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Phone Number</label>
                                                    <div class="col-sm-12">                                          
				                                        <%= f.text_field :staff_phone, :class=>'form-control', :placeholder=>"Enter Staff Phone", :required=>''  %>
				                                    </div>
				                                </div>
				                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Email</label>
                                                    <div class="col-sm-12">                                          
				                                        <%= f.text_field :staff_email, :class=>'form-control', :placeholder=>"Enter Staff Email", :type=>'email', :required=>''  %>
				                                    </div>
				                                </div>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label class="col-xs-12" for="example-password-input">Sex</label>
                                                            <div class="col-sm-12"> 
                                                                <%= f.select :staff_sex, options_for_select([ 'Male', 'Female'], :selected => 'Male'), {:include_blank => false}, {:class=>'form-control'} %>
                                                            </div>
                                                        </div>
                                                    </div> 
                                                    <div class="col-md-6"> 
                                                        <div class="form-group">
                                                            <label class="col-xs-12" for="example-password-input">Salary</label>
                                                            <div class="col-sm-12">                                            
                                                                <%= f.text_field :staff_salary, :class=>'form-control', :placeholder=>"Enter Total Salary", :type=>'number', :required=>''  %>
                                                             
                                                            </div>
                                                        </div>  
                                                    </div>                                              
                                                </div>                                      
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Address</label>
                                                    <div class="col-sm-12">                                           
                                                        <%= f.text_area :staff_address, :class=>'form-control', :placeholder=>"Enter Staff Address", :rows=>'2', :required=>''  %>
                                                    </div>
                                                </div>                                               
                                      
                                                <div class="form-group">
                                                    <div class="col-sm-12">
                                                        <%= f.submit :class=>'btn btn-sm btn-primary', :value=>'submit' %>
                                                    </div>
                                                </div>

                                            <% end %>
                                        </div>    
                                    </div>    
                                </div>
                            </div>
                        </div>
                    </div>        
                </div>

app/views/staffs/show.html.erb
			
                <% content_for :title, "Staff Details" %>


                <div class="content content-boxed">
                    <div class="block">
                        <div class="bg-image" style="background-image: url('<%= asset_path('dashboard.jpg') %>')">
                            <div class="block-content bg-primary-dark-op text-center overflow-hidden">
                                <div class="push-30-t push animated fadeInDown">
                                    <%= image_tag "user.png", :class=>'img-avatar img-avatar96 img-avatar-thumb' %>
                                </div>
                                <div class="push-30 animated fadeInUp">
                                    <h2 class="h4 font-w600 text-white push-5"><%= @staff.staff_name %></h2>
                                    <h3 class="h5 text-gray"><%= @staff.staff_address %></h3>
                                </div>
                            </div>
                        </div>
                        <div class="block-content text-center">
                            <div class="row items-push text-uppercase">
                                <div class="col-md-4">
                                    <div class="font-w700 text-gray-darker animated fadeIn">Phone</div>
                                    <a class="h2 font-w300 text-primary animated flipInX"><%= @staff.staff_phone %></a>
                                </div>
                                <div class="col-md-4">
                                    <div class="font-w700 text-gray-darker animated fadeIn">Email</div>
                                    <a class="h2 font-w300 text-primary animated flipInX"><%= @staff.staff_email %></a>
                                </div>
                                <div class="col-md-4">
                                    <div class="font-w700 text-gray-darker animated fadeIn">Sex</div>
                                    <a class="h2 font-w300 text-primary animated flipInX"><%= @staff.staff_sex %></a>
                                </div>
                            </div>
                        </div>  
                    </div>
                </div>


                <!-- Page Content -->
                <div class="content">                    
                    <!-- Dynamic Table Simple -->
                    <div class="block">
                        <div class="block-header">
                            <ul class="block-options">
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                                </li>
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                                </li>
                            </ul>
                             <h3 class="block-title">Order <small>Records</small></h3>
                        </div>
                        <div class="block-content table-responsive">
                            <!-- DataTables init on table by adding .js-dataTable-simple class, functionality initialized in js/pages/base_tables_datatables.js -->
                            <table class="table table-striped js-dataTable-full-pagination">
                                <thead>
                                    <tr>
                                        <th>Salary Date</th>
                                        <th>Salary Amount</th>
                                        <th>Salary Month</th>
                                        <th>Salary Paid</th>
                                    </tr>
                                </thead> 
                                <tbody>
                                    <% @staff_salary.each do |salary|  %>
                                        <tr>
                                            <td><%= salary.salary_date %></td>
                                            <td><%= salary.staff.staff_salary %></td>
                                            <td><%= salary.salary_month %></td>
                                            <td><%= salary.salary_paid %></td>
                                        </tr>
                                    <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div> 
                </div>
                <!-- END Page Content -->