config/routes.rb
Rails.application.routes.draw do

  root :to => 'dashboards#index'

  resources :dashboards
  resources :customers do 
    resources :measurements

    member do 
      get 'get_customer_measurements'
    end
  end
  resources :orders
  resources :staffs
  resources :salaries  

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  belongs_to :user
  has_many :measurements
  accepts_nested_attributes_for :measurements
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :authenticate_user!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
    @customer_order = Order.where(:customer_id=> params[:id], :order_delete=>'0')
    @measurements = @customer.measurements

    @customer_order_amount = Order.where(:customer_id=> params[:id], :order_delete=>'0').sum(:order_amount)
    @customer_order_paid = Order.where(:customer_id=> params[:id], :order_delete=>'0').sum(:order_paid)
    @customer_order_total = @customer_order.count
  end

  def new
    @customer = Customer.new
  end

  def create
    begin      
      @customer = current_user.customers.create!(customer_params)      
      if @customer.present?
        redirect_to customer_path(@customer), notice: 'Customer was successfully created.'
      else
        redirect_to new_customer_path, :alert=> 'Customer was not created.'
      end  
    rescue Exception => e
      puts "#{e.message}"
    end
    
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])

    if @customer.update(customer_params)
      redirect_to customers_path, :notice=> 'Customer was successfully updated.'
    else
      redirect_to edit_customers_path, :alert=> 'Customer was not updated.'
    end
  end

  def destroy
    @customer = Customer.find(params[:id])

    if @customer.destroy
      redirect_to customers_path, :notice=> 'Customer was successfully deleted.'
    end    
  end

  def get_customer_measurements    
    customer = Customer.find(params[:id])
    @customer_measurments = customer.measurements

    respond_to do |format|
      format.json {render :json => @customer_measurments}
    end
  end
private
  def customer_params
    params.require(:customer).permit(:customer_name, :customer_phone, :customer_email, :customer_sex, :customer_address, measurements_attributes: [:name, :neck, :shoulder, :chest, :waist, :hips, :sleeve, :bicep, :wrist, :length, :thigh, :crotch, :ankles, :inseam, :outseam, :other_measurements])
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
				<% content_for :title, "Edit Customer" %>


             	<!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Edit Customer <small>Edit Existing Customer Data.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Dashbord</li>
                                <li><a class="link-effect" href="">Edit Customer</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                	<div class="row">
                        <div class="col-md-12">
							<div class="block">
		                        <div class="block-header">
		                            <ul class="block-options">
										<li>
											<button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
										</li>
										<li>
											<button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
										</li>
									</ul>
		                            <h3 class="block-title">Customer Form <small>Requierd</small></h3>
		                        </div>
		                        <div class="block-content block-content-narrow">									
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<%= form_for @customer, :html=>{:class=>'form-horizontal push-10-t'} do|f| %>
												<div class="form-group">
				                                    <label class="col-xs-12" for="example-password-input">Name</label>
													<div class="col-sm-12">
			                                        	<%= f.text_field :customer_name, :class=>'form-control', :placeholder=>"Enter Customer Name", :required=>''  %>		
				                                    </div>
				                                </div>										
			                                	<div class="form-group">
				                                    <label class="col-xs-12" for="example-password-input">Email</label>
													<div class="col-sm-12">                                           
				                                        <%= f.text_field :customer_email, :class=>'form-control', :placeholder=>"Enter Customer Email", :type=>'email', :required=>''  %>		
				                                    </div>
				                                </div>
				                                <div class="row">
					                                <div class="col-md-6">
					                                	<div class="form-group">
						                                    <label class="col-xs-12" for="example-password-input">Phone Number</label>
															<div class="col-sm-12">                                           
						                                       	<%= f.text_field :customer_phone, :class=>'form-control', :placeholder=>"Enter Customer Phone", :required=>''  %>
						                                    </div>
						                                </div>
					                                </div>
					                                <div class="col-md-6">
						                                <div class="form-group">
						                                    <label class="col-xs-12" for="example-password-input">Sex</label>
															<div class="col-sm-12"> 
				                                        	<%= f.select :customer_sex, options_for_select([ 'Male', 'Female'], :selected => f.object.customer_sex), {:include_blank => false}, {:class=>'form-control'} %>
				                                            </div>
						                                </div>
				                                	</div>				                                	
				                                </div>    
				                                <div class="form-group">
				                                    <label class="col-xs-12" for="example-password-input">Address</label>
													<div class="col-sm-12">                                           
				                                        <%= f.text_area :customer_address, :class=>'form-control', :placeholder=>"Enter Customer Address", :required=>''  %>
				                                    </div>
				                                </div>
				                                <div class="form-group">
				                                    <div class="col-sm-12">
				                                        <%= f.submit :class=>'btn btn-sm btn-primary', :value=>'submit' %>
				                                    </div>
				                                </div>
		                            		<% end %>
		                            	</div>	
		                            </div>		
		                        </div>
		                    </div>
		                </div>
		            </div>        
                </div>    
  

app/views/customers/index.html.erb
                
                <% content_for :title, "Customers" %>


                <!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Customer <small>All Customers Data.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Dashbord</li>
                                <li><a class="link-effect" href="">Customer</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                    <!-- Dynamic Table Simple -->
                    <div class="block">
                        <div class="block-header">
                            <ul class="block-options">
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                                </li>
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                                </li>
                            </ul>
                            <h3 class="block-title">Customer <small>Records</small></h3>
                        </div>
                        <div class="block-content table-responsive">
                            <!-- DataTables init on table by adding .js-dataTable-simple class, functionality initialized in js/pages/base_tables_datatables.js -->
                            <table class="table table-striped js-dataTable-full-pagination">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>Phone</th>
                                        <th>Email</th>
                                        <th>sex</th>
                                        <th>Address</th>
                                        <th class="text-center">Actions</th>
                                    </tr>
                                </thead> 
                                <tbody>
                                  <% @customers.each do |customer|  %>
                                    <tr><td>C-<%= customer.id %></td>
                                        <td><%= customer.customer_name %></td>
                                        <td><%= customer.customer_phone %></td>
                                        <td><%= customer.customer_email %></td>
                                        <td><%= customer.customer_sex %></td>
                                        <td><%= customer.customer_address %></td>
                                        <td class="text-center">
                                            <div class="btn-group">
                                                <%= link_to customer_path(customer.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-eye"></i>
                                                <% end %>
                                                <%= link_to edit_customer_path(customer.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-pencil"></i>
                                                <% end %>
                                                <%= link_to customer_path(customer.id), :class=>'btn btn-xs btn-default', method: :delete, data: {confirm: 'Are you sure to delete customer?'} do %>
                                                    <i class="fa fa-trash-o"></i>
                                                <% end %>
                                            </div>  
                                        </td>    
                                    </tr>
                                  <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div> 
                </div>
                <!-- END Page Content -->

app/views/customers/new.html.erb
				<% content_for :title, "Add Customer" %>


             	<!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Add Customer <small>Add New Customer Data.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Dashbord</li>
                                <li><a class="link-effect" href="">Add Customer</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                	<div class="row">
                        <div class="col-md-12">
							<div class="block">
		                        <div class="block-header">
		                            <ul class="block-options">
										<li>
											<button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
										</li>
										<li>
											<button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
										</li>
									</ul>
		                            <h3 class="block-title">Customer Form <small>Requierd</small></h3>
		                        </div>
		                        <div class="block-content block-content-narrow">
		                        	<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<%= form_for @customer, :html=>{:class=>'form-horizontal push-10-t'} do|f| %>										
												<div class="form-group">
				                                    <label class="col-xs-12" for="example-password-input">Name</label>
													<div class="col-sm-12">
			                                        	<%= f.text_field :customer_name, :class=>'form-control', :placeholder=>"Enter Customer Name", :required=>''  %>		
				                                    </div>
				                                </div>										
			                                	<div class="form-group">
				                                    <label class="col-xs-12" for="example-password-input">Email</label>
													<div class="col-sm-12">                                           
				                                        <%= f.text_field :customer_email, :class=>'form-control', :placeholder=>"Enter Customer Email", :type=>'email', :required=>''  %>		
				                                    </div>
				                                </div>
				                                <div class="row">
					                                <div class="col-md-6">
					                                	<div class="form-group">
						                                    <label class="col-xs-12" for="example-password-input">Phone Number</label>
															<div class="col-sm-12">                                           
						                                       	<%= f.text_field :customer_phone, :class=>'form-control', :placeholder=>"Enter Customer Phone", :required=>''  %>
						                                    </div>
						                                </div>
					                                </div>
					                                <div class="col-md-6">
						                                <div class="form-group">
						                                    <label class="col-xs-12" for="example-password-input">Sex</label>
															<div class="col-sm-12"> 
					                                        	<%= f.select :customer_sex, options_for_select([ 'Male', 'Female'], :selected => 'Male'), {:include_blank => false}, {:class=>'form-control'} %>
						                                    </div>
						                                </div>
				                                	</div>				                                	
				                                </div>    
				                                <div class="form-group">
				                                    <label class="col-xs-12" for="example-password-input">Address</label>
													<div class="col-sm-12">                                           
				                                        <%= f.text_area :customer_address, :class=>'form-control', :placeholder=>"Enter Customer Address", :required=>''  %>
				                                    </div>
				                                </div>
				                                <div class="form-group">
				                                    <div class="col-sm-12">
				                                        <%= f.submit :class=>'btn btn-sm btn-primary', :value=>'submit' %>
				                                    </div>
				                                </div>

			                            	<% end %>
			                            </div>	
		                            </div>	
		                        </div>
		                    </div>
		                </div>
		            </div>        
                </div>    
  

app/views/customers/show.html.erb
                <% content_for :title, "Customer Details" %>


                <div class="content content-boxed">
                  <div class="block">
                    <div class="bg-image" style="background-image: url('<%= asset_path('dashboard_3.jpg') %>')">
                        <div class="block-content bg-primary-dark-op text-center overflow-hidden">
                            <div class="push-30-t push animated fadeInDown">
                                <%= image_tag "user.png", :class=>"img-avatar img-avatar96 img-avatar-thumb" %>
                            </div>
                            <div class="push-30 animated fadeInUp">
                                <h2 class="h4 font-w600 text-white push-5"><%= @customer.customer_name %></h2>
                                <h3 class="h5 text-gray"><%= @customer.customer_address %></h3>
                            </div>
                        </div>
                    </div>
                    <div class="block-content text-center">
                      <div class="row items-push text-uppercase">
                        <div class="col-md-3">
                          <div class="font-w700 text-gray-darker animated fadeIn">Total Order</div>
                          <a class="h2 font-w300 text-primary animated flipInX"><%= @customer_order_total %></a>
                        </div>                               
                        <div class="col-md-3">
                          <div class="font-w700 text-gray-darker animated fadeIn">Total Amount</div>
                          <a class="h2 font-w300 text-primary animated flipInX"><%= @customer_order_amount %></a>
                        </div>
                        <div class="col-md-3">
                          <div class="font-w700 text-gray-darker animated fadeIn">Total Paid</div>
                          <a class="h2 font-w300 text-primary animated flipInX"><%= @customer_order_paid %></a>
                        </div>
                        <div class="col-md-3">
                          <div class="font-w700 text-gray-darker animated fadeIn">Total Due</div>
                          <a class="h2 font-w300 text-primary animated flipInX"><%= @customer_order_amount - @customer_order_paid %></a>
                        </div>
                      </div>
                    </div>  
                  </div>
                </div>

                <div class="text-right" style="margin-right: 30px">
                  <%= link_to new_customer_measurement_path(@customer), :class=>'btn btn-danger' do %>
                    Add Measurement
                  <% end %>
                </div>                            

                <!-- Page Content -->
                <div class="content">                    
                  <!-- Dynamic Table Simple -->
                  <div class="block">
                    <div class="block-header">
                        <ul class="block-options">
                            <li>
                                <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                            </li>
                            <li>
                                <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                            </li>
                        </ul>
                        <h3 class="block-title">Measurements</h3>
                    </div>

                    <div class="block-content table-responsive">
                      <!-- DataTables init on table by adding .js-dataTable-simple class, functionality initialized in js/pages/base_tables_datatables.js -->
                      <table class="table table-striped js-dataTable-full-pagination">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th class="text-center">Actions</th>  
                            </tr>
                        </thead> 
                        <tbody>
                            <% @measurements.each do |measurement| %>
                                <tr>
                                  <td><%= measurement.name %></td>
                                  <td class="text-center">
                                    <div class="btn-group">
                                      <%= link_to customer_measurement_path(@customer.id, measurement.id), :class=>'btn btn-xs btn-default' do %>
                                          <i class="fa fa-eye"></i>
                                      <% end %>
                                      <%= link_to edit_customer_measurement_path(@customer.id, measurement.id), :class=>'btn btn-xs btn-default' do %>
                                          <i class="fa fa-pencil"></i>
                                      <% end %>
                                      <%= link_to customer_measurement_path(@customer.id, measurement.id), :class=>'btn btn-xs btn-default', method: :delete, data: {confirm: 'Are you sure to delete measurement?'} do %>
                                          <i class="fa fa-trash-o"></i>
                                      <% end %>
                                    </div>  
                                  </td>    
                                </tr>
                            <% end %>
                        </tbody>
                      </table>
                    </div>
                  </div> 
                </div>

                <div class="content">                    
                  <!-- Dynamic Table Simple -->
                  <div class="block">
                    <div class="block-header">
                      <ul class="block-options">
                          <li>
                              <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                          </li>
                          <li>
                              <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                          </li>
                      </ul>
                      <h3 class="block-title">Order <small>Records</small></h3>
                    </div>
                    <div class="block-content table-responsive">
                      <!-- DataTables init on table by adding .js-dataTable-simple class, functionality initialized in js/pages/base_tables_datatables.js -->
                      <table class="table table-striped js-dataTable-full-pagination">
                        <thead>
                          <tr>
                            <th>Delivery Date</th>
                            <th>Amount</th>
                            <th>Paid</th>
                            <th>Order Status</th>
                          </tr>
                        </thead> 
                        <tbody>
                          <% @customer_order.each do |order|  %>
                            <tr>
                              <td><%= order.delivery_date %></td>
                              <td><%= order.order_amount %></td>
                              <td><%= order.order_paid %></td>
                              <% if order.order_status == 'Confirm'  %>
                                  <td class="text-left"><span class="label label-default"> <%= order.order_status %></span></td>
                              <% elsif order.order_status == 'Processing' %>
                                  <td class="text-left"><span class="label label-warning"> <%= order.order_status %></span></td>
                              <% elsif order.order_status == 'Ready' %>
                                  <td class="text-left"><span class="label label-success"> <%= order.order_status %></span></td>
                              <% elsif order.order_status == 'Delivered' %>
                                  <td class="text-left"><span class="label label-primary"> <%= order.order_status %></span></td>    
                              <% end %>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>
                    </div>
                  </div> 
                </div>
                <!-- END Page Content -->