config/routes.rb
Rails.application.routes.draw do

  root :to => 'dashboards#index'

  resources :dashboards
  resources :customers do 
    resources :measurements

    member do 
      get 'get_customer_measurements'
    end
  end
  resources :orders
  resources :staffs
  resources :salaries  

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :staff
  has_many :order_measurements
  has_many :measurements, through: :order_measurements
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user!	

  def index
    @orders = Order.where(:order_delete=>'0')
  end

  def show
    @order  = Order.find(params[:id])
  end

  def new
    @order = Order.new
    @customer = Customer.all
    @staff = Staff.all
  end

  def create
    @order = Order.new(order_params)

    measurement_ids = params[:order][:measurement_ids].select(&:presence)
    if @order.save
      measurement_ids.each do |m_id|
        @order.order_measurements.create({measurement_id: m_id})  
      end
      redirect_to orders_path, notice: 'Order was successfully created.'
    else
      render new_order_path, :alert=> 'Order was not created.'
    end
  end

  def edit
  	@order = Order.find(params[:id])
  	@customer = Customer.all
    @staff = Staff.where(:staff_delete=>'0')
    @measurements = @order.measurements
  end

  def update
    @order = Order.find(params[:id])

  	if @order.update(order_params)
      redirect_to orders_path, notice: 'Order was successfully updated.'
    else
      redirect_to edit_orders_path, :alert=> 'Order was not updated.'
    end
  end

  def destroy
  	if @order = Order.where(:id=>params[:id]).update_all(:order_delete=>'1')
      redirect_to orders_path, notice: 'Order was successfully deleted.'
    end
  end
private
  def order_params
    params.require(:order).permit(:customer_id, :staff_id, :delivery_date, :order_amount, :order_paid, :order_status, :order_details)    
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.erb
<% content_for :title, "Edit Order" %>

<!-- Page Header -->
<div class="content bg-gray-lighter">
  <div class="row items-push">
      <div class="col-sm-7">
          <h1 class="page-heading animated zoomIn">
              Edit Order <small>Edit Existing Order Data.</small>
          </h1>
      </div>
      <div class="col-sm-5 text-right hidden-xs">
          <ol class="breadcrumb push-10-t">
              <li>Dashbord</li>
              <li><a class="link-effect" href="">Edit Order</a></li>
          </ol>
      </div>
  </div>
</div>
<!-- END Page Header -->

<!-- Page Content -->
<div class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="block">
        <div class="block-header">
          <ul class="block-options">
            <li>
              <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
            </li>
            <li>
              <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
            </li>
          </ul>
          <h3 class="block-title">Order Form <small>Requierd</small></h3>
        </div>
        <div class="block-content block-content-narrow">
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <%= form_for @order, :html=>{:class=>'form-horizontal push-10-t'} do|f| %>
                
                <div class="form-group">
                  <label class="col-xs-12" for="example-password-input">Staff Name</label>
                  <div class="col-sm-12"> 
                    <% options = options_from_collection_for_select(@staff, 'id', 'staff_name', :selected => f.object.staff_id) %>
                      <%= f.select :staff_id, options, {:include_blank => false}, {:class=>'form-control select_list', :style=>"width:100%"}  %>
                  </div>
                </div>  

                <div class="form-group">
                  <label class="col-xs-12" for="example-password-input">Customer Name</label>
                  <div class="col-sm-12">
                    <% options = options_from_collection_for_select(@customer, 'id', 'customer_name', :selected => f.object.customer_id) %>
                    <%= f.select :customer_id, options, {:include_blank => false}, {:class=>'form-control select_list', :style=>"width:100%"} %>
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-xs-12" for="example-password-input">Measurements</label>
                  <div class="col-sm-12"> 
                    <% @measurements.each do |o_m| %>
                      <p><%= o_m.name %></p>
                    <% end %>
                  </div>
                </div>                                    
                
                <div class="form-group">
                  <label class="col-xs-12" for="example-password-input">Delivery Date</label>
                  <div class="col-sm-12">                                            
                    <%= f.text_field :delivery_date, :class=>'form-control', :type=>"date", :required=>''  %>
                  </div>
                </div> 
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label class="col-xs-12" for="example-password-input">Amount</label>
                      <div class="col-sm-12">                                            
                        <%= f.text_field :order_amount, :class=>'form-control', :placeholder=>"Enter Total Amount", :type=>'number', :required=>''  %>
                      </div>
                    </div> 
                  </div>
                  <div class="col-md-6">                                                
                    <div class="form-group">
                        <label class="col-xs-12" for="example-password-input">Paid</label>
                        <div class="col-sm-12">                                            
                            <%= f.text_field :order_paid, :class=>'form-control', :placeholder=>"Enter Paid Amount", :type=>'number', :required=>''  %>
                        </div>
                    </div>                                                        
                  </div> 
                </div>   
                <div class="form-group">
                  <label class="col-xs-12" for="example-password-input">Order Details</label>
                  <div class="col-sm-12">                                            
                    <%= f.text_area :order_details, :class=>'form-control', :placeholder=>"Enter Order Details", :rows=>'2', :required=>''  %>
                  </div>
                </div>                         
                <div class="form-group">
                  <div class="col-xs-12">
                      <div class="form-material">   
                          <label>Status</label>                                     
                          <div class="col-xs-12">
                              <div class="row">
                                  <div class="col-md-3"><label class="css-input css-radio css-radio-default"><%= f.radio_button :order_status, 'Confirm', :class=>'icheckbox_square-green' %><span></span> Confirm </label></div>
                                  <div class="col-md-3"><label class="css-input css-radio css-radio-warning"><%= f.radio_button :order_status, 'Processing', :class=>'icheckbox_square-green' %><span></span> Processing </label></div>
                                  <div class="col-md-3"><label class="css-input css-radio css-radio-success"><%= f.radio_button :order_status, 'Ready', :class=>'icheckbox_square-green' %><span></span> Ready </label></div>
                                  <div class="col-md-3"><label class="css-input css-radio css-radio-primary"><%= f.radio_button :order_status, 'Delivered', :class=>'icheckbox_square-green' %><span></span> Delivered </label></div>
                              </div>   
                          </div>
                      </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-12">
                    <%= f.submit :class=>'btn btn-sm btn-primary', :value=>'submit' %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>                            
        </div>
      </div>
    </div>        
  </div>                          
</div>

app/views/orders/index.html.erb
<% content_for :title, "Orders" %>


<!-- Page Header -->
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-7">
        <h1 class="page-heading animated zoomIn">
            Order <small>All Orders Data.</small>
        </h1>
    </div>
      <div class="col-sm-5 text-right hidden-xs">
        <ol class="breadcrumb push-10-t">
          <li>Dashbord</li>
          <li><a class="link-effect" href="">Order</a></li>
        </ol>
      </div>
  </div>
</div>
<!-- END Page Header -->

<!-- Page Content -->
<div class="content">
  <!-- Dynamic Table Simple -->
  <div class="block">
    <div class="block-header">
      <ul class="block-options">
          <li>
              <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
          </li>
          <li>
              <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
          </li>
      </ul>
      <h3 class="block-title">Order <small>Records</small></h3>
    </div>
      <div class="block-content table-responsive">
        <table class="table table-striped js-dataTable-full-pagination">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Phone</th>
              <th>Address</th>
              <th>Assign To</th>
              <th>Amount</th>
              <th>Due</th>
              <th>Delivery Date</th>
              <th>Order Status</th>
              <th class="text-center">Actions</th>
            </tr>
          </thead> 
          <tbody>
            <% @orders.each do |order|  %>
              <tr>
                <td>O-<%= order.id %></td>
                <td data-toggle="popover" title="Details" data-content="<%= order.order_details %>" data-placement="top"><%= order.customer.customer_name %></td>
                <td><%= order.customer.customer_phone %></td>
                <td><%= order.customer.customer_address %></td>
                <td><%= order.staff.staff_name %></td>
                <td data-toggle="popover" title="Paid" data-content="<%= order.order_paid %>" data-placement="top"><%= order.order_amount %></td>
                <td><%= order.order_amount - order.order_paid %></td>
                <td><%= order.delivery_date %></td>
                <% if order.order_status == 'Confirm'  %>
                    <td class="text-center"><span class="label label-default"> <%= order.order_status %></span></td>
                <% elsif order.order_status == 'Processing' %>
                    <td class="text-center"><span class="label label-warning"> <%= order.order_status %></span></td>
                <% elsif order.order_status == 'Ready' %>
                    <td class="text-center"><span class="label label-success"> <%= order.order_status %></span></td>
                <% elsif order.order_status == 'Delivered' %>
                    <td class="text-center"><span class="label label-primary"> <%= order.order_status %></span></td>    
                <% end %>
                <td class="text-center">
                    <div class="btn-group">
                        <%= link_to order_path(order.id), :class=>'btn btn-xs btn-default' do %>
                            <i class="fa fa-print"></i>
                        <% end %>
                        <%= link_to edit_order_path(order.id), :class=>'btn btn-xs btn-default' do %>
                            <i class="fa fa-pencil"></i>
                        <% end %>   
                        <%= link_to order_path(order.id), :class=>'btn btn-xs btn-default', method: :delete, data: {confirm: 'Are you sure?'} do %>
                            <i class="fa fa-trash-o"></i>
                        <% end %> 
                    </div>
                </td>    
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
  </div> 
</div>
<!-- END Page Content -->

app/views/orders/new.html.erb
<% content_for :title, "Add Order" %>

<!-- Page Header -->
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-7">
      <h1 class="page-heading animated zoomIn">
          Add Order <small>Add New Order Data.</small>
      </h1>
    </div>
    <div class="col-sm-5 text-right hidden-xs">
      <ol class="breadcrumb push-10-t">
          <li>Dashboard</li>
          <li><a class="link-effect" href="">Add Order</a></li>
      </ol>
    </div>
  </div>
</div>
<!-- END Page Header -->

<!-- Page Content -->
<div class="content">
  <div class="row">
    <div class="col-md-12">                    
      <div class="block">
        <div class="block-header">
            <ul class="block-options">
                <li>
                    <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                </li>
                <li>
                    <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                </li>
            </ul>
            <h3 class="block-title">Order Form</h3>
        </div>
        <div class="block-content block-content-narrow">
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <%= form_for @order, :html=>{:class=>'form-horizontal push-10-t'} do|f| %>
                <div class="form-group">
                  <label class="col-xs-12" for="example-password-input">Staff Name</label>
                  <div class="col-sm-12"> 
                    <% options = options_from_collection_for_select(@staff, 'id', 'staff_name') %>
                    <%= f.select :staff_id, options, {:include_blank => false}, {:class=>'form-control select_list', :style=>"width:100%"}  %>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-xs-12" for="example-password-input">Customer Name</label>
                  <div class="col-sm-12">
                    <% options = options_from_collection_for_select(@customer, 'id', 'customer_name') %>
                    <%= f.select :customer_id, options, {:prompt => 'Select Customer'}, {:class=>'form-control select_list', :style=>"width:100%"} %>
                  </div>
                </div>                
                <div class="form-group">
                  <label class="col-xs-12" for="example-password-input">Measurements</label>
                  <div class="col-sm-12">
                    <%= f.collection_select :measurement_ids, {}, :id, :name, {}, {multiple: true, :style=>"width:100%", :required => true}%>
                  </div>
                </div>
                <div class="form-group">
                    <label class="col-xs-12" for="example-password-input">Delivery Date</label>
                    <div class="col-sm-12">                                            
                        <%= f.text_field :delivery_date, :class=>'form-control', :type=>"date", :required=>''%>
                    </div>
                </div> 
                <div class="row">
                    <div class="col-md-6">                                                           
                        <div class="form-group">
                            <label class="col-xs-12" for="example-password-input">Amount</label>
                            <div class="col-sm-12">                                            
                                    <%= f.text_field :order_amount, :class=>'form-control', :placeholder=>"Enter Total Amount", :type=>'number', :required=>''  %>
                            </div>
                        </div> 
                    </div>
                    <div class="col-md-6">                                                
                        <div class="form-group">
                            <label class="col-xs-12" for="example-password-input">Paid</label>
                            <div class="col-sm-12">                                            
                                <%= f.text_field :order_paid, :class=>'form-control', :placeholder=>"Enter Paid Amount", :type=>'number', :required=>''  %>
                            </div>
                        </div>                                                        
                    </div> 
                </div>   
                <div class="form-group">
                    <label class="col-xs-12" for="example-password-input">Order Details</label>
                    <div class="col-sm-12">                                            
                        <%= f.text_area :order_details, :class=>'form-control', :placeholder=>"Enter Order Details", :rows=>'2', :required=>''  %>
                    </div>
                </div>                         
                <div class="form-group">
                    <div class="col-xs-12">
                        <div class="form-material">   
                            <label>Status</label>                                     
                            <div class="col-xs-12">
                                <div class="row">
                                    <div class="col-md-3"><label class="css-input css-radio css-radio-default"><%= f.radio_button :order_status, 'Confirm', :class=>'icheckbox_square-green' %><span></span> Confirm </label></div>
                                    <div class="col-md-3"><label class="css-input css-radio css-radio-warning"><%= f.radio_button :order_status, 'Processing', :class=>'icheckbox_square-green' %><span></span> Processing </label></div>
                                    <div class="col-md-3"><label class="css-input css-radio css-radio-success"><%= f.radio_button :order_status, 'Ready', :class=>'icheckbox_square-green' %><span></span> Ready </label></div>
                                    <div class="col-md-3"><label class="css-input css-radio css-radio-primary"><%= f.radio_button :order_status, 'Delivered', :class=>'icheckbox_square-green' %><span></span> Delivered </label></div>
                                </div>   
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-12">
                        <%= f.submit :class=>'btn btn-sm btn-primary', :value=>'submit' %>
                    </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>        
  </div>        
</div>


<script type="text/javascript">
  $(document).ready(function(){
    $(document).on("change", '#order_customer_id', function() {
      $('#order_measurement_ids').empty();
      var customer_id = this.value;
      
      $.ajax({
         url: "/customers/"+customer_id+"/get_customer_measurements", //+SELLERID,
         type: "GET",
         dataType: "json",
         
         success: function(data) {
          console.log(data);
          var x = document.getElementById("order_measurement_ids");            

           for (i = 0; i < data.length; i++) {
             var option = document.createElement("option");
              option.text = data[i]['name'];
              option.value = data[i]['id']
              x.add(option);
            }
         },
         error: function(data) {
           alert("Please select a valid customer.");
         }
       });
    });
  });
</script>

app/views/orders/show.html.erb
<% content_for :title, "Print Order" %>

<!-- Page Header -->
<!-- You can use the .hidden-print class to hide an element in printing -->
<div class="content bg-gray-lighter hidden-print">
    <div class="row items-push">
        <div class="col-sm-7">
            <h1 class="page-heading animated zoomIn">
                Invoice <small>Print Order Invoice.</small>
            </h1>
        </div>
        <div class="col-sm-5 text-right hidden-xs">
            <ol class="breadcrumb push-10-t">
                <li>Generic</li>
                <li><a class="link-effect" href="">Invoice</a></li>
            </ol>
        </div>
    </div>
</div>
<!-- END Page Header -->

<!-- Page Content -->
<div class="content content-boxed">
    <!-- Invoice -->
    <div class="block">
        <div class="block-header">
            <ul class="block-options">
                <li>
                    <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"></button>
                </li>
                <li>
                    <!-- Print Page functionality is initialized in App() -> uiHelperPrint() -->
                    <button type="button" onclick="App.initHelper('print-page');"><i class="si si-printer"></i> Print Invoice</button>
                </li>
            </ul>
        </div>
        <div class="block-content block-content-narrow">
            <!-- Company Info -->
            <div class="row">
                <!-- Company Info -->
                <div class="col-xs-6">
                    <p class="h2 font-w400 push-5" style="margin-bottom: 20px !important">
                        Al-Azhar Enterprises
                    </p>
                </div>  
                <div class="col-xs-6 pull-right text-right">
                    <div class="h3 pull-right" style="margin-top: 10px !important">
                        INVOICE 
                        <h5>#INV-<%= @order.id %></h5>
                    </div>
                </div> 
            </div>      
            <!-- Invoice Info -->                            
            <hr style="margin-top: 0px;">
            <div class="row items-push-2x">
                <!-- Company Info -->
                <div class="col-xs-6 col-sm-4 col-lg-3">
                  <p class="h5 push-5"><b>Customer Info</b></p>
                  <h5><%= @order.customer.customer_name %></h5>
                  <address>
                    <%= @order.customer.customer_address %><br>
                    <i class="si si-call-end"></i> <%= @order.customer.customer_phone %>
                  </address>                    
                </div>
                <!-- END Company Info -->

                <!-- Client Info -->
                <div class="col-xs-6 col-sm-4 col-sm-offset-4 col-lg-3 col-lg-offset-6 text-right">
                    <p class="h5 push-5"><b>Print Date</b><br> <%= DateTime.now.to_date %></p>
                    <p class="h5 push-5"><b>Delivery Date</b><br> <%= @order.delivery_date %></p>
                </div>
                <!-- END Client Info -->                                
            </div>
            <!-- END Invoice Info -->

            <!-- Table -->
            <div class="table-responsive push-50">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 50px;"></th>
                            <th>Particulars</th>
                            <th class="text-center" style="width: 120px;">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @order.measurements.each_with_index do |measurement, index| %>
                          <tr>
                            <td class="text-center"><%= (index + 1) %></td>
                            <td>
                              <p class="font-w600 push-10"><%= measurement.name %></p>
                            </td>
                            <% if index == 0 %>
                              <td rowspan= "<%= @order.measurements.count %>" class="text-center"> <%= @order.order_amount %></td>
                            <% end %>
                          </tr>  
                        <% end %>
                        <tr>
                            <td colspan="2" class="font-w600 text-right">Total</td>
                            <td class="text-center"> <%= @order.order_amount %> </td>
                        </tr>
                        <tr>
                            <td colspan="2" class="font-w600 text-right">Advance</td>
                            <td class="text-center"> <%= @order.order_paid %></td>
                        </tr>
                        <tr class="active">
                            <td colspan="2" class="font-w700 text-uppercase text-right">Balance</td>
                            <td class="font-w700 text-center"> <%= (@order.order_amount - @order.order_paid) %></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <!-- END Table -->

            <!-- Footer -->
            <hr class="hidden-print">
            <p class="text-muted text-center"><small>Thank you very much for doing business with us. We look forward to working with you again!</small></p>
            <!-- END Footer -->
        </div>
    </div>
    <!-- END Invoice -->
</div>
<!-- END Page Content -->