config/routes.rb
Rails.application.routes.draw do

  root :to => 'dashboards#index'

  resources :dashboards
  resources :customers do 
    resources :measurements

    member do 
      get 'get_customer_measurements'
    end
  end
  resources :orders
  resources :staffs
  resources :salaries  

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/salary.rb
class Salary < ApplicationRecord
  belongs_to :staff
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController

  before_action :authenticate_user!
  
  def index
    @salaries = Salary.all
  end

  def show
     @salary = Salary.find(params[:id])
  end

  def new
    @salary = Salary.new
    @staff = Staff.where(:staff_delete=>'0')
  end

  def create
    @salary = Salary.new(params.require(:salary).permit(:staff_id, :salary_date, :salary_month, :salary_paid))

    if @salary.save
      redirect_to salaries_path, :notice=> 'Salary was successfully created.'
    else
      redirect_to new_salaries_path, :alert=> 'Salary was not created.'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/views/salaries/index.html.erb
                <% content_for :title, "Salaries" %>


  				<!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Salary <small>All Salaries Data.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Dashbord</li>
                                <li><a class="link-effect" href="">Salary</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                    <!-- Dynamic Table Simple -->
                    <div class="block">
                        <div class="block-header">
                            <ul class="block-options">
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                                </li>
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                                </li>
                            </ul>
                            <h3 class="block-title">Salary <small>Records</small></h3>
                        </div>
                        <div class="block-content table-responsive">
                            <!-- DataTables init on table by adding .js-dataTable-simple class, functionality initialized in js/pages/base_tables_datatables.js -->
                            <table class="table table-striped js-dataTable-full-pagination">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Staff Name</th>
									    <th>Staff Phone</th>
									    <th>Salary Month</th>
									    <th>Staff Salary</th>
									    <th>Salary Paid</th>
									    <th>Paid Date</th>
                                        <th class="text-center">Actions</th>
                                    </tr>
                                </thead> 
                                <tbody>
                                  <% @salaries.each do |salary|  %>
                                    <tr>
                                        <td>W-<%= salary.id %></td>
                                        <td><%= salary.staff.staff_name %></td>
								        <td><%= salary.staff.staff_phone %></td>
								        <td><%= salary.salary_month %></td>
								        <td><%= salary.staff.staff_salary %></td>
								        <td><%= salary.salary_paid %></td>
								        <td><%= salary.salary_date %></td> 
                                        <td class="text-center">
                                            <div class="btn-group">
                                                <%= link_to salary_path(salary.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-print"></i>
                                                <% end %>
                                            </div>
                                        </td>          
                                    </tr>
                                  <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- END Page Content -->

app/views/salaries/new.html.erb
                <% content_for :title, "Add Salary" %>


				<!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Add Salary <small>Add New Salary Data.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Dashbord</li>
                                <li><a class="link-effect" href="">Add Salary</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                	<div class="row">
                        <div class="col-md-12">
                            <div class="block">
                                <div class="block-header">
                                    <ul class="block-options">
                                        <li>
                                            <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                                        </li>
                                        <li>
                                            <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                                        </li>
                                    </ul>
                                    <h3 class="block-title">Salary Form <small>Requierd</small></h3>
                                </div>
                                <div class="block-content block-content-narrow">
                                    <div class="row">
                                        <div class="col-md-6 col-md-offset-3">
                                            <%= form_for @salary, :html=>{:class=>'form-horizontal push-10-t'} do|f| %>			
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Staff Name</label>
                                                    <div class="col-sm-12"> 
                                                        <% options = options_from_collection_for_select(@staff, 'id', 'staff_name') %>
                                                        <%= f.select :staff_id, options, {:include_blank => false}, {:class=>'form-control select_list', :style=>'width: 100%'}  %>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label class="col-xs-12" for="example-password-input">Month</label>
                                                            <div class="col-sm-12">
                                                                <%= f.select :salary_month, options_for_select([ 'January', 'February','March','April','May','June','July','August','September', 'October', 'November' , 'December']), {:include_blank => false}, {:class=>'form-control'} %>  
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                         <div class="form-group">
                                                            <label class="col-xs-12" for="example-password-input">Salary Paid</label>
                                                            <div class="col-sm-12">                                          
                                                                <%= f.text_field :salary_paid, :class=>'form-control', :placeholder=>"Enter Paid Amount", :type=>'number', :required=>''  %>                                                        
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div> 
                                                <%= f.hidden_field :salary_date, :value=> Time.now %>
                                                <div class="form-group">
                                                    <div class="col-sm-12">
                                                        <%= f.submit :class=>'btn btn-sm btn-primary', :value=>'submit' %>
                                                    </div>
                                                </div>
                                            <% end %>
                                        </div>
                                    </div>    
                                </div>
    		                </div>
                        </div>    
		            </div>        
                </div>   

app/views/salaries/show.html.erb
                <% content_for :title, "Print Order" %>


                <!-- Page Header -->
                <!-- You can use the .hidden-print class to hide an element in printing -->
                <div class="content bg-gray-lighter hidden-print">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Invoice <small>Print Order Invoice.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Generic</li>
                                <li><a class="link-effect" href="">Invoice</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content content-boxed">
                    <!-- Invoice -->
                    <div class="block">
                        <div class="block-header">
                            <ul class="block-options">
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"></button>
                                </li>
                                <li>
                                    <!-- Print Page functionality is initialized in App() -> uiHelperPrint() -->
                                    <button type="button" onclick="App.initHelper('print-page');"><i class="si si-printer"></i> Print Invoice</button>
                                </li>
                            </ul>
                        </div>
                        <div class="block-content block-content-narrow">
                            <!-- Company Info -->
                            <div class="row">
                                <!-- Company Info -->
                                <div class="col-xs-6">
                                    <p class="h2 font-w400 push-5" style="margin-bottom: 20px !important">
                                        <%= image_tag 'rose-logo-min.png' %> ROSE TMS 
                                    </p>
                                </div>  
                                <div class="col-xs-6 pull-right text-right">
                                    <div class="h3 pull-right" style="margin-top: 10px !important">
                                        AUTHOR COPY 
                                        <h5>#W-<%= @salary.id %></h5>
                                    </div>
                                </div> 
                            </div>      
                            <!-- Invoice Info -->                            
                            <hr style="margin-top: 0px;">
                            <div class="row items-push-2x">
                                <!-- Company Info -->
                                <div class="col-xs-6">
                                    <p class="h5 push-5"><b>Customer Info</b></p>
                                    <h5><%= @salary.staff.staff_name %></h5>
                                    <address>
                                        <%= @salary.staff.staff_address %><br>
                                        <i class="si si-call-end"></i> <%= @salary.staff.staff_phone %>
                                    </address>
                                </div>
                                <!-- END Company Info -->

                                <div class="col-xs-2">
                                    <p class="h5 push-5"><b>Salary Month</b><br>
                                    <%= @salary.salary_month %>
                                </div>

                                <div class="col-xs-2">
                                    <p class="h5 push-5"><b>Payment Date</b><br> <%= @salary.salary_date %></p>
                                </div>

                                <div class="col-xs-2 text-right">
                                    <p class="h5 push-5"><b>Paid Amount</b><br>
                                    $ <%= @salary.salary_paid %>
                                </div>                                
                            </div>
                            <!-- END Invoice Info -->

                            <div class="row">
                                <div class="col-xs-2 text-center">
                                    __________________
                                    <br> Author Sign
                                </div>
                                <div class="col-xs-2 text-center col-xs-offset-8">
                                    __________________
                                    <br> Staff Sign
                                </div>                                
                            </div>

                            <hr style="margin-top: 50px; margin-bottom: 50px;">

                            <!-- Company Info -->
                            <div class="row">
                                <!-- Company Info -->
                                <div class="col-xs-6">
                                    <p class="h2 font-w400 push-5" style="margin-bottom: 20px !important">
                                        <%= image_tag 'rose-logo-min.png' %> ROSE TMS 
                                    </p>
                                </div>  
                                <div class="col-xs-6 pull-right text-right">
                                    <div class="h3 pull-right" style="margin-top: 10px !important">
                                        STAFF COPY 
                                        <h5>#W-<%= @salary.id %></h5>
                                    </div>
                                </div> 
                            </div>     
                            <!-- Invoice Info -->                            
                            <hr style="margin-top: 0px;">
                            <div class="row items-push-2x">
                                <!-- Company Info -->
                                <div class="col-xs-6">
                                    <p class="h5 push-5"><b>Customer Info</b></p>
                                    <h5><%= @salary.staff.staff_name %></h5>
                                    <address>
                                        <%= @salary.staff.staff_address %><br>
                                        <i class="si si-call-end"></i> <%= @salary.staff.staff_phone %>
                                    </address>
                                </div>
                                <!-- END Company Info -->

                                <div class="col-xs-2">
                                    <p class="h5 push-5"><b>Salary Month</b><br>
                                    <%= @salary.salary_month %>
                                </div>

                                <div class="col-xs-2">
                                    <p class="h5 push-5"><b>Payment Date</b><br> <%= @salary.salary_date %></p>
                                </div>

                                <div class="col-xs-2 text-right">
                                    <p class="h5 push-5"><b>Paid Amount</b><br>
                                    $ <%= @salary.salary_paid %>
                                </div>                             
                            </div>

                            <div class="row">
                                <div class="col-xs-2 text-center">
                                    __________________
                                    <br> Author Sign
                                </div>
                                <div class="col-xs-2 text-center col-xs-offset-8">
                                    __________________
                                    <br> Staff Sign
                                </div>                                
                            </div>

                            <!-- Footer -->
                            <hr class="hidden-print">
                            <p class="text-muted text-center hidden-print"><small>Thank you very much for doing business with us. We look forward to working with you again!</small></p>
                            <!-- END Footer -->
                        </div>
                    </div>
                    <!-- END Invoice -->
                </div>
                <!-- END Page Content -->